#!/bin/bash
#Copyright 2002 Michal Zalewski

echo "p0frep p0f log analyzer by <lcamtuf@coredump.cx>"

if [ $# -lt 2 ]; then
	cat >/dev/stderr <<EOHELP
Usage:

p0frep logfile.txt sortby [ 'ipmask' 'sysmask' ]

    logfile.txt    - input file
    sortby         - 'system' or 'addr'; sort order
    ipmask         - IP mask, e.g. 195.117.3. (can be '')
    sysmask        - system name mask, e.g. 'Windows'

Typical usage might be:

To get your local systems in 10.0 subnet sorted by OS name:
  p0frep log.txt system 10.0.
To get all AIX boxes sorted by IP:
  p0frep log.txt addr '' AIX

...and so on
EOHELP
	exit 1
fi

if [ ! -f "$1" ]; then
  echo "No filename given." >/dev/stderr
  exit 1
fi

if [ "$2" = "system" ]; then
  cat "$1" | grep -F ']:' | sed -e 's/\[.*\]: /: /g;s/ \*//g' | awk -F': ' '{print $2 ": " $1}' | sort -n | uniq | awk -F': ' '{print $2 ": " $1}' | grep -F "$3" | grep -F "$4"
elif [ "$2" = "addr" ]; then
  cat "$1" | grep -F ']:' | sed -e 's/\[.*\]: /: /g;s/ \*//g' | sort -n | uniq | grep -F "$3" | grep -F "$4"
else
  echo "Second parameter (sort order) mst be 'system' or 'addr'." >/dev/stderr
  exit 1
fi

